after-login-command = []

start-at-login = false

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 300

default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = false

[[on-window-detected]]
if.app-name-regex-substring = 'finder'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'whatsapp'
run = 'layout floating'

[[on-window-detected]]
check-further-callbacks = true
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'telegram'
run = 'layout floating'

[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 24
inner.vertical =   24
outer.left =       24
outer.bottom =     24
outer.top =        24
outer.right =      24

[mode.main.binding]

cmd-h = [] # Disable "hide application"
cmd-alt-h = [] # Disable "hide others"

alt-comma = 'layout tiles horizontal vertical'
alt-shift-comma = 'layout accordion horizontal vertical'

alt-ctrl-shift-f = 'fullscreen'
alt-ctrl-f = 'layout floating tiling'

alt-shift-left = 'join-with left'
alt-shift-down = 'join-with down'
alt-shift-up = 'join-with up'
alt-shift-right = 'join-with right'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-shift-n = 'resize smart -50'
alt-shift-m = 'resize smart +50'

alt-q = 'workspace 1'
alt-w = 'workspace 2'
alt-e = 'workspace 3'
alt-a = 'workspace 4'
alt-s = 'workspace 5'

alt-shift-q = 'move-node-to-workspace 1'
alt-shift-w = 'move-node-to-workspace 2'
alt-shift-e = 'move-node-to-workspace 3'
alt-shift-a = 'move-node-to-workspace 4'
alt-shift-s = 'move-node-to-workspace 5'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-ctrl-s = 'mode service'
alt-ctrl-t = 'mode typing'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

[mode.typing.binding]
esc = 'mode main'

